.TH JAG 1 "November 2025" "1.0.0" "Jaguar User Manual"
.SH NAME
jag \- Live reloading for your ESP32
.SH SYNOPSIS
.B jag
[OPTIONS] [COMMAND]
.SH DESCRIPTION
Jaguar enables live reloading of Toit code when developing for the ESP32.
.PP
Develop, update, and restart your code in less than two seconds via WiFi.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show help for jag
.SH COMMANDS
.TP
.B completion
Generate the autocompletion script for the specified shell
.TP
.B config
Configure Jaguar
.TP
.B container
Manipulate the set of installed containers on a device
.TP
.B decode
Decode a stack trace received from a Jaguar device
.TP
.B firmware
Show or update firmware for a Jaguar device
.TP
.B flash
Flash an ESP32 with the Jaguar firmware
.TP
.B help
Help about any command
.TP
.B monitor
Monitor the serial output of an ESP32
.TP
.B ping
Ping a Jaguar device to see if it is active
.TP
.B pkg
Manage packages
.TP
.B port
Get current port or list available ports
.TP
.B run
Run Toit code on a Jaguar device
.TP
.B scan
Scan for Jaguar devices
.TP
.B setup
Setup the Toit SDK
.TP
.B simulate
Start a simulated Jaguar device on your machine
.TP
.B toit
Run 'toit' commands through Jaguar
.TP
.B version
Prints the version of Jaguar
.TP
.B watch
Watch for changes to <file> and its dependencies and automatically re-run the code
.SH SEE ALSO
.BR toit (1)
.br
https://github.com/toitlang/jaguar
