name: Update homebrew

on:
  release:
    # Note that edited doesn't trigger when the prerelease flag is changed.
    # One would also need to change the description slightly.
    types: [ released, edited ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && !github.event.release.prerelease
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.LEON_REPOSITORY_DISPATCH }}
          repository: toitlang/homebrew-toit
          event-type: new-release
          client-payload: '{"ref": "${{ github.ref_name }}"}'
