name: Winget

on:
  release:
    types: [published]

jobs:
  winget:
    name: Publish winget package
    runs-on: windows-latest
    steps:
      - name: Download winget binary
        run: |
          iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe

      - name: Update manifest
        run: |
          $github = Get-Content '${{ github.event_path }}' | ConvertFrom-Json
          $installerUrl = $github.release.assets | Where-Object -Property name -match 'jag_installer.exe' | Select -ExpandProperty browser_download_url -First 1

          .\wingetcreate.exe update Toit.Jaguar -s -v $github.release.tag_name -u $installerUrl -t ${{ secrets.WINGET_JAGUAR_PAT }}
